* fixed: #778 -- Idea run dialog was not saving Sim details if no device is attached and selected in preferred device udid (#779)
exception:
> java.lang.NullPointerException: Cannot read field "id" because the return value of "org.robovm.idea.running.RoboVmIOSRunConfigurationSettingsEditor$Decorator.from(javax.swing.JComboBox)" is null

(cherry picked from commit 7080cc85053f5effdde7afd237577ce640115b42)